# Run in R 3.5.2
source('global.R')

shinyUI(fluidPage(theme="yeti.css",
                  shinyjs::useShinyjs(),
                  div(
                    id = "loading_page",
                    h1("Loading...")
                  ),
                  hidden(
                    div(
                      id = "main_content",
                      # suppress error messages as data loads, hacky
                      tags$style(type="text/css",
                                 ".shiny-output-error { visibility: hidden; }",
                                 ".shiny-output-error:before { visibility: hidden; }"
                      ),
                      navbarPage(paste("NRSA ",assessmentCycle," Rapid Data Extraction and Reporting Tool", sep=''),
                                 tabPanel('About',
                                          fluidRow(column(3,br(),br(),br(),p('Some sort of sweet river picture with people sampling')),
                                                   column(8,h2(strong('Tool Overview')),
                                                          h5('The Rapid Data Extraction and Reporting Tool expedites data availability
                                                             to field crews and offers preliminary end-of-day site reports to landowners to 
                                                             promote survey awareness and continued sampling support. '), 
                                                          br(),
                                                          h5('After completing all sampling, sample processing, and data upload procedures to the ',span(strong('EPA SERVER??')), 
                                                             'users can expect to receive a record of all data submitted to their NARS user email address. The json file 
                                                             format precludes some users from accessing data, so this tool compiles the json files into spreadsheet formats to 
                                                             promote data utility and offers and optional site report based on immediate data such as field parameters, taxa 
                                                             lists, and XXXX to be sent by the team lead to the landowner within ',span(strong('48 hours')),' of sampling.', 
                                                             span(strong('Bold statement, I know, we can discuss for sure'))),
                                                          br(),
                                                          h5('Please direct all questions related to tool troubleshooting and feature requests to
                                                             Karen Blocksom (Blocksom.Karen@epa.gov) and Emma Jones (emma.jones@deq.virginia.gov).')),
                                                   column(1)),
                                          
                                          br(),hr(),br(),
                                          fluidRow(column(1),
                                                   column(10,h3(strong('Instructions')),
                                                          p('After receiving all json files from the server, users will create a single directory to house all data for record
                                                            keeping purposes. On the Data Upload and Extraction tab, users will select the directory where their data is saved 
                                                            to upload json files to the app for processing. Once the data is uploaded to the app, users will have the option 
                                                            to save the data as individual .csv files or a single MS Excel spreadsheet containing sheets of each dataset.'),
                                                          br(),
                                                          p('If the users wants to generate an end-of-day site report for their records or to distribute to the landowner, they may navigate
                                                            to the Landowner Report tab and follow the on screen prompts to save an autogenerated HTML file based on their input site data.')),
                                                   column(1))  ),
                                 tabPanel('Data Upload and Extraction',
                                          sidebarPanel(h4(strong('Instructions')),
                                                       p('1) Choose the directory where you have saved all json files associated with a single sample site. A list of all
                                                         file names within the directory will be available for preview to the right when they are available to the app.'),
                                                       shinyDirButton('directory', 'Select Directory', 'Please select a folder'), br(),
                                                       p('2) Click the Upload button below when you are ready to analyze all data in the selected directory.'),
                                                       actionButton('uploadFiles','Upload all files in selected directory'), br(),
                                                       p('3) If you want to save the parsed files to the local directory, please choose the appropriate output file 
                                                         format and click the Save Results button.'),
                                                       radioButtons('fileFormat', 'Output File Format', choices = c('.csv', '.xlsx')),
                                                       downloadButton("download","Save Results in Selected File Format")),
                                          
                                          mainPanel(
                                            h5('Preview files in directory'),
                                            tableOutput('preview')#,
                                            #p('verbatim1'),
                                            #verbatimTextOutput('verbatim1')
                                            #p('verbatim2'),
                                            #verbatimTextOutput('verbatim2'),
                                            #p('verbatim3'),
                                            #verbatimTextOutput('verbatim3'),
                                            #p('verbatim4'),
                                            #verbatimTextOutput('verbatim4')
                                                    )),
                                 tabPanel('Landowner Report')
                      )
                    ))
                  ))
                                          