# Run in R 3.5.2
source('global.R')

shinyUI(fluidPage(theme="yeti.css",
                  shinyjs::useShinyjs(),
                  div(
                    id = "loading_page",
                    h1("Loading...")
                  ),
                  hidden(
                    div(
                      id = "main_content",
                      # suppress error messages as data loads, hacky
                      tags$style(type="text/css",
                                 ".shiny-output-error { visibility: hidden; }",
                                 ".shiny-output-error:before { visibility: hidden; }"
                      ),
                      navbarPage(paste("NRSA ",assessmentCycle," Rapid Data Extraction and Reporting Tool", sep=''),
                                 tabPanel('About',
                                          fluidRow(column(3,br(),br(),br(),img(src='oregon_stream.png',align='left')),
                                                   column(8,h2(strong('Tool Overview')),
                                                          p('The Rapid Data Extraction and Reporting Tool expedites data availability
                                                            to field crews and offers preliminary end-of-day site reports to landowners to 
                                                            promote survey awareness and continued sampling support. '), 
                                                          br(),
                                                          p('After completing all sampling and sample processing, crews submit data from the app to ',
                                                            span(strong('NARS IM.')),'At that point, all of the .JSON files from that site visit
                                                            and collected on that iPad will be attached to an email to NARS IM. The crew can copy that email to other
                                                            addresses and later save those .JSON files (and any from other iPads used at that site) to a folder 
                                                            containing all of the data collected from an individual site visit.
                                                            This tool parses and compiles the data from .JSON files into spreadsheet formats to 
                                                            promote data utility and offers and optional site report based on field-collected data, such as field 
                                                            parameters and lists of fish species collected, to be sent by the team lead to the landowner shortly 
                                                            after sampling.'),
                                                          br(),
                                                          p('Please direct all questions related to tool troubleshooting and feature requests to
                                                            Karen Blocksom (Blocksom.Karen@epa.gov) and Emma Jones (emma.jones@deq.virginia.gov).')),
                                                   column(1)),
                                          
                                          br(),hr(),br(),
                                          fluidRow(column(1),
                                                   column(10,h3(strong('Instructions')),
                                                          p('After compiling all of the .JSON files for a site visit into a single directory, users are ready to extract 
                                                            and organize the data. On the Data Upload and Extraction tab, users select the directory where their data is saved 
                                                            to upload .JSON files to the app for processing. Once the data is uploaded to the app, users will have the option 
                                                            to save the data as a .zip file containing individual .csv files or a single MS Excel spreadsheet containing   
                                                            worksheets of each dataset.'),
                                                          br(),
                                                          p('After uploading the data, if users want to generate a basic site report for their records or to distribute to the
                                                            landowner, they may navigate to the Landowner Report tab and follow the on screen prompts to save an autogenerated
                                                            HTML file based on their input site data.')),
                                                   column(1))  ),
                                 tabPanel('Data Upload and Extraction',
                                          sidebarPanel(h4(strong('Instructions')),
                                                       p('1) Choose the directory where you have saved all of the .JSON files associated with a single site visit. A list of all
                                                         file names within the directory will be available for preview to the right when they are available to the app.'),
                                                       shinyDirButton('directory', 'Select Directory', 'Please select a folder'), br(),
                                                       p('2) Click the Upload button below when you are ready to analyze all data in the selected directory.'),
                                                       actionButton('uploadFiles','Upload all files in selected directory'), br(),
                                                       p('3) If you want to save the parsed files to the local directory, please click the download button for the appropriate
                                                         output file format. The buttons will not be available until the data is finished processing.
                                                         Once the buttons are available, you may download data. Note: saving as .csv will download a 
                                                         .zip of all .csv files. All downloads will be saved to your downloads folder.'),
                                                       downloadButton("downloadxlsx","Save Results as .xlsx"),
                                                       downloadButton("downloadcsv","Save Results as .csv")),
                                          
                                          mainPanel(
                                            h5('Preview files in directory'),
                                            tableOutput('preview'))),
                                 tabPanel('Landowner Report',
                                          sidebarPanel(h3('This tool creates a basic report in html format based on data collected during a field visit to a site. 
                                                          It can be saved for crew records or provided to the landowner, either via email or printed and mailed.')),
                                          mainPanel(downloadButton('report','Generate Landowner Report (HTML)')))
                        )
                    ))
                  )
)
                                          